spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.prod.url}
    username: ${database.prod.username}
    password: ${database.prod.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  config:
    activate:
      on-profile: prod
    import:
      - submodule/security/database.yml
